### ISSUE TITLE
启用不成功

### ISSUE THREAD

**Issue by nature2608** [maxlicheng/luci-app-unblockmusic#53]
`{ Error: connect ECONNREFUSED 59.111.21.14:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '59.111.21.14',
  port: 443 }
`
日志提示
设备：dw33d
固件：L大源码自编译
内核：4.9.192
没有开其他代理软件

**Comment by maxlicheng** [comment]
git pull更新插件源码。。UnblockNeteaseMusic 更新至v0.19.2才不会保存。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nature2608 <notifications@github.com&gt;
发送时间: 2019年9月16日 20:02
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 启用不成功 (#53)




{ Error: connect ECONNREFUSED 59.111.21.14:443 at Object._errnoException (util.js:1022:11) at _exceptionWithHostPort (util.js:1044:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14) code: 'ECONNREFUSED', errno: 'ECONNREFUSED', syscall: 'connect', address: '59.111.21.14', port: 443 } 
日志提示
设备：dw33d
固件：L大源码自编译
内核：4.9.192
没有开其他代理软件

**Comment by closernow** [comment]
很抱歉提出如此幼稚问题，不过我想要更新到192版本的话，我再putty里面应该输入什么命令？我现在是191版本，也是无法启动，启动后几秒钟就停止运行

**Comment by maxlicheng** [comment]
什么路由器，发行版中目前有新三，x86，n1下载安装即可，没有则需要自己编译。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: closernow <notifications@github.com&gt;
发送时间: 2019年9月16日 21:12
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 启用不成功 (#53)




很抱歉提出如此幼稚问题，不过我想要更新到192版本的话，我再putty里面应该输入什么命令？我现在是191版本，也是无法启动，启动后几秒钟就停止运行

**Comment by closernow** [comment]
> 什么路由器，发行版中目前有新三，x86，n1下载安装即可，没有则需要自己编译。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: closernow <notifications@github.com&gt; 发送时间: 2019年9月16日 21:12 收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt; 抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[maxlicheng/luci-app-unblockmusic] 启用不成功 (#53) 很抱歉提出如此幼稚问题，不过我想要更新到192版本的话，我再putty里面应该输入什么命令？我现在是191版本，也是无法启动，启动后几秒钟就停止运行 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

我的是新3

**Comment by maxlicheng** [comment]
在这里下载就可以了：https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.0-1/newifid2.zip



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: closernow <notifications@github.com&gt;
发送时间: 2019年9月16日 21:16
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 启用不成功 (#53)



 
什么路由器，发行版中目前有新三，x86，n1下载安装即可，没有则需要自己编译。 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: closernow <notifications@github.com&gt; 发送时间: 2019年9月16日 21:12 收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt; 抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[maxlicheng/luci-app-unblockmusic] 启用不成功 (#53) 很抱歉提出如此幼稚问题，不过我想要更新到192版本的话，我再putty里面应该输入什么命令？我现在是191版本，也是无法启动，启动后几秒钟就停止运行 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
我的是新3

**Comment by closernow** [comment]
谢谢作者耐心回复，我已下载了，但是不知道如何传到路由器安装，我再查查资料吧，我刚开始以为可以用ssh一个命令就可以升级

**Comment by nature2608** [comment]
@maxlicheng 我看了下源码的确是版本问题，我删掉重新编译进固件试试。谢谢你！
@closernow 先把原来的卸载掉（在软件源里搜索卸载掉），把下载的用winscp放进去tmp目录，用putty `cd /tmp` 安装`opkg install 文件名`

**Comment by closernow** [comment]
@nature2608 好，我去试试
